package vn.gmi.workzen.utils

object IntentData {

    val KEY_VIEW = "KEY_VIEW"
    val KEY_CONVERSATION_ID = "KEY_CONVERSATION_ID"
    val KEY_DATA_FROM_FCM = "KEY_DATA_FROM_FCM"
    val KEY_MRZ_INFO = "KEY_MRZ_INFO"
    val KEY_TYPE_MRZ_INFO = "KEY_TYPE_MRZ_INFO"
    val KEY_NFC = "KEY_NFC"
    val KEY_EPPASSPORT_RESULT = "KEY_EPPASSPORT_RESULT"

    val KEY_QRCODE_INFO = "KEY_QR_CODE_RESULT"
    val KEY_CAN_KEY = "KEY_CAN_KEY"
    val KEY_MODE_SCAN_NFC = "KEY_MODE_SCAN_NFC"
}